### PR TITLE
Throw an exception when parsing an invalid query

### PR DESCRIPTION
**Pull request by viebel**

### CODE REVIEW

**Comment by retro** [comment]
@viebel Thank you!

**Comment by retro** [comment]
Version 0.0.14 is released with this included.

**Comment by viebel** [comment]
Wow! That was fast.
Could you please cut a new release soon?

**Comment by retro** [comment]
https://github.com/retro/graphql-builder/pull/24#issuecomment-706002587 😉

**Comment by viebel** [comment]
Cool!

**Pull request merged**
